# Generated by Django 2.0.3 on 2020-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midd19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='prime',
            field=models.IntegerField(null=True),
        ),
    ]
