# Generated by Django 3.0.7 on 2020-07-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midd19', '0002_comment_prime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='prime',
            new_name='p_id',
        ),
    ]
