# Generated by Django 2.0.3 on 2020-07-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midd19', '0002_comment_prime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='prime',
            new_name='postid',
        ),
    ]
