# Generated by Django 3.0.7 on 2020-07-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midd19', '0003_auto_20200703_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='p_id',
            new_name='prime',
        ),
    ]
